apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-consumer-deployment
  namespace: cloud-events
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
    spec:
      serviceAccountName: consumer-sa
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: cloud-event-consumer
          image: cloud-event-consumer
          imagePullPolicy: Always
          args:
            - "--local-api-addr=consumer-events-subscription-service.cloud-events.svc.cluster.local:9043"
            - "--api-path=/api/ocloudNotifications/v2/"
            - "--http-event-publishers=ptp-event-publisher-service-NODE_NAME.openshift-ptp.svc.cluster.local:9043"
            - "--auth-config=/etc/cloud-event-consumer/auth/config.json"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONSUMER_TYPE
              value: "PTP"
            - name: ENABLE_STATUS_CHECK
              value: "true"
          volumeMounts:
            - name: pubsubstore
              mountPath: /store
            - name: client-certs
              mountPath: /etc/cloud-event-consumer/client-certs
              readOnly: true
            - name: ca-bundle
              mountPath: /etc/cloud-event-consumer/ca-bundle
              readOnly: true
            - name: auth-config
              mountPath: /etc/cloud-event-consumer/auth
              readOnly: true
      volumes:
        - name: pubsubstore
          emptyDir: {}
        - name: client-certs
          secret:
            secretName: consumer-client-certs
        - name: ca-bundle
          secret:
            secretName: server-ca-bundle
        - name: auth-config
          configMap:
            name: consumer-auth-config
