apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    service.alpha.openshift.io/serving-cert-secret-name: sidecar-consumer-secret
  name: consumer-sidecar-service
  namespace: cloud-events
  labels:
    app: consumer-service
spec:
  ports:
    - name: metrics
      port: 8443
      targetPort: https
  selector:
    app: consumer
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: consumer-sidecar-service-monitor
  name: consumer-sidecar-service-monitor
  namespace: cloud-events
spec:
  jobLabel: cloud-events
  endpoints:
    - interval: 30s
      port: metrics
      bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
      scheme: "https"
      tlsConfig:
        caFile: "/etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt"
        serverName: "consumer-sidecar-service.cloud-events.svc"
  selector:
    matchLabels:
      app: consumer-service
  namespaceSelector:
    matchNames:
      - cloud-events
